# Generated by Django 5.1.7 on 2025-06-14 03:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id_project', models.AutoField(primary_key=True, serialize=False)),
                ('nama_project', models.CharField(max_length=255)),
                ('model', models.CharField(max_length=255)),
                ('deskripsi', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Kinerja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_performance', models.CharField(max_length=255)),
                ('evaluation_metrics', models.CharField(max_length=255)),
                ('hyperparameters', models.CharField(max_length=255)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kinerja', to='dataentry.project')),
            ],
        ),
        migrations.CreateModel(
            name='DataTransaksi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deskripsi_data', models.TextField()),
                ('input_file', models.FileField(upload_to='transaksi_files/')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_transaksi', to='dataentry.project')),
            ],
        ),
        migrations.CreateModel(
            name='DataLingkungan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ram', models.CharField(max_length=100)),
                ('database', models.CharField(max_length=100)),
                ('cpu', models.CharField(max_length=100)),
                ('os', models.CharField(max_length=100)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_lingkungan', to='dataentry.project')),
            ],
        ),
        migrations.CreateModel(
            name='CatatanPemeliharaan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suggest', models.TextField()),
                ('category', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=50)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('stakeholder', models.CharField(blank=True, max_length=255, null=True)),
                ('role', models.CharField(blank=True, max_length=255, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catatan_pemeliharaan', to='dataentry.project')),
            ],
        ),
        migrations.CreateModel(
            name='AktivitasImplementasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_type', models.CharField(max_length=255)),
                ('algorithm_used', models.CharField(max_length=255)),
                ('hyperparameters', models.CharField(max_length=255)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aktivitas_implementasi', to='dataentry.project')),
            ],
        ),
    ]
