# Generated by Django 5.2.3 on 2025-06-19 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dataentry", "0002_remove_kinerja_evaluation_metrics_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="external_id",
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
