# Generated by Django 5.1.7 on 2025-06-11 11:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataentry', '0002_catatanpemeliharaan_end_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kinerja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_performance', models.CharField(max_length=255)),
                ('evaluation_metrics', models.CharField(max_length=255)),
                ('hyperparameters', models.CharField(max_length=255)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kinerja', to='dataentry.project')),
            ],
        ),
    ]
