# Generated by Django 5.2.3 on 2025-06-19 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dataentry", "0003_project_external_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="datalingkungan",
            name="input_file",
            field=models.FileField(
                blank=True, null=True, upload_to="lingkungan_files/"
            ),
        ),
    ]
