# Generated by Django 5.1.7 on 2025-06-12 13:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataentry', '0003_kinerja'),
    ]

    operations = [
        migrations.CreateModel(
            name='AktivitasImplementasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_type', models.CharField(max_length=255)),
                ('algorithm_used', models.CharField(max_length=255)),
                ('hyperparameters', models.CharField(max_length=255)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aktivitas_implementasi', to='dataentry.project')),
            ],
        ),
    ]
